### PR TITLE
Github raw url and curl fixes

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by dasilvacontin** [comment]
@mvdan, squash commits.

**Comment by mvdan** [comment]
Each commit does a different thing.

**Comment by mvdan** [comment]
Ping @keroserene

**Comment by keroserene** [comment]
We already have plenty of commits that are at the level of "bunch of README updates" or larger - squashing these 3 sounds reasonable to me and would prevent commit history bloat, if you don't mind :)
Thank you!

**Comment by mvdan** [comment]
I don't think this is commit history bloat as long as each commit does a different thing :) This way, if something breaks, you can pinpoint it to a single commit and revert it since it only did that thing, instead of partially reverting a "bug fixes" commit that does three things at a time.

If you still want me to squash before merging, I can squash them.

**Comment by keroserene** [comment]
Totally agreed in general, although these are 3 miniscule changes to a README and I don't find there's risk of future break pinpointing shenanigans in this case. Please squash ;)

**Comment by mvdan** [comment]
Done.

**Comment by keroserene** [comment]
Thanks for spending time on this thing :+1:

**Comment by mvdan** [comment]
Ha, now that I have contributed to rickrollrc my life is finally complete!

**Comment by dasilvacontin** [comment]
Now you can run forever mvdon!

**Comment by mllobet** [comment]
corre mvdon

**Pull request merged**
